apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    addon: aws-sdk-prom-metrics
    app: aws-sdk-prom-metrics
  name: aws-sdk-prom-metrics
  namespace: kube-system
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: aws-sdk-prom-metrics
  strategy:
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      annotations:
        proxy.istio.io/config: '{ "holdApplicationUntilProxyStarts": true }'
      labels:
        app: aws-sdk-prom-metrics
    spec:
      containers:
      - name: app
        image: 361053881171.dkr.ecr.eu-west-1.amazonaws.com/platform/aws-sdk-prom-metrics:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
          name: metrics
          protocol: TCP
        resources:
          limits:
            memory: 512Mi
          requests:
            cpu: 400m
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            add:
            - NET_BIND_SERVICE
            drop:
            - ALL
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
        seccompProfile:
          type: RuntimeDefault
      serviceAccount: terraform-operator
      serviceAccountName: terraform-operator
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoExecute
        key: afterpay.cloud/newNodes
        operator: Exists
      nodeSelector:
        afterpay.cloud/newNodes: "true"
