apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  labels:
    addon: aws-sdk-prom-metrics
    app: aws-sdk-prom-metrics
  name: aws-sdk-prom-metrics
  namespace: kube-system
spec:
  namespaceSelector:
    matchNames:
    - kube-system
  podMetricsEndpoints:
  - interval: 300s
    path: /metrics
    port: metrics
    scrapeTimeout: 30s
  selector:
    matchLabels:
      app: aws-sdk-prom-metrics
